server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/userdb}
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/Maradga}

  cache:
    type: redis
    redis:
      time-to-live: 600000

keycloak:
  server-url: http://localhost:9090
  realm: Maradga
  client-id: banking-system
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches,env
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 0.0

logging:
  level:
    org.springframework.security: DEBUG
    com.miaoubich.banking: DEBUG
