server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 

  cache:
    type: redis
    redis:
      time-to-live: 600000

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

keycloak:
  server-url: http://localhost:9090
  realm: Maradga
  client-id: banking-system
  client-secret: k670S5pYEb1YSXcuS8KHJxQzF0OhJtbl

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches,env
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 0.0

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: DEBUG
    com.miaoubich.banking: DEBUG
