server:
  port: 8082

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/Maradga

  cache:
    type: redis
    redis:
      time-to-live: 600000

  # zipkin:
  #   base-url: http://localhost:9411
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

keycloak:
  server-url: http://localhost:9090
  realm: Maradga
  client-id: banking-system
  client-secret: k670S5pYEb1YSXcuS8KHJxQzF0OhJtbl

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches,env
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 0.0

# Monitoring stack disabled (Zipkin, Prometheus, Grafana)
# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info,caches,metrics,env,prometheus
#   endpoint:
#     health:
#       show-details: always
#     prometheus:
#       enabled: true
#   # Micrometer configuration
#   tracing:
#     sampling:
#       probability: 0.0  # Disable tracing
#   # Prometheus configuration
#   prometheus:
#     metrics:
#       export:
#         enabled: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: DEBUG
    com.miaoubich.banking: DEBUG
