server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: notification-service	
  kafka:
    template:
         default-topic: banking.account-transaction
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false #for safer offset management in financial systems
    listener:
      ack-mode: manual
      properties:
        spring.json.trusted.packages: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

logging:
  level:
    com.miaoubich.banking: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info